name: nist-frvt-analysis

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.7
  - pip
  - beautifulsoup4
  - bokeh
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - lxml
  - matplotlib
  - nb_conda
  - numpy
  - pandas
  - pandas-profiling
  - seaborn
  - simplejson
  - tabulate
  - umap-learn
